export const CDN_PATH = 'https://3gimg.qq.com/lightmap/xcx/demoCenter/images';
export const COS_PATH = 'https://mapapi.qq.com/web/miniprogram/demoCenter/images'
export const PLUGIN_KEY = '3EOBZ-S7BW6-ANYSI-EDFXQ-5TG7F-K3BSS';
export const MOYUAN_KEY = '3EOBZ-S7BW6-ANYSI-EDFXQ-5TG7F-K3BSS';
export const BAIQIAN_KEY = '3EOBZ-S7BW6-ANYSI-EDFXQ-5TG7F-K3BSS';
export const YULU_KEY = '3EOBZ-S7BW6-ANYSI-EDFXQ-5TG7F-K3BSS';
export const DIFUNI_KEY = '3EOBZ-S7BW6-ANYSI-EDFXQ-5TG7F-K3BSS';
export const INDOOR_KEY = '3EOBZ-S7BW6-ANYSI-EDFXQ-5TG7F-K3BSS';
export const REFERER = '生命规划线';
export const WEBSERVICE_APPID = 'wxc1c68623b7bdea7b';
export const CUSTOM_KEY = ''; // 个性化地图key
export const WS_HOST = 'https://apis.map.qq.com'
export const SMART_SOLUTION_KEY = ''; //出行解决方案key